### ISSUE TITLE
Avatars not consistently applied

### ISSUE THREAD

**Issue by tarragon** [buildkite/frontend#27]
Semi-recently I believe there was a switch to Gravatar based avatars for the frontend. This doesn't seem to be working universally. My logged in avatar works in the upper right corner for my profile drop-down menu, but on all my builds it is still using the placeholder "?" avatar.

![good](https://cloud.githubusercontent.com/assets/7235/14446574/f6c7f4a6-009a-11e6-8b08-d4022f637abe.png)

![bad](https://cloud.githubusercontent.com/assets/7235/14446580/07b55038-009b-11e6-943c-8bc7681329eb.png)

**Comment by keithpitt** [comment]
Hey hey! So the reason you're seeing a "?" on that build is because we haven't correctly linked that build to your Buildkite user account. When we create a build, we look at the associated email address, find a user with a verified matching email, and link the two. Once they're linked, you should start seeing your face :)

So to fix this, check the "Environment" tab for that build, and find the `BUILDKITE_BUILD_CREATOR_EMAIL` value - that's the email that we're missing on your user account. Add that email to your account, and it should be good after that :) We need to make that linking process smoother, and call out on the build page if it's not correctly linked though!

**Comment by tarragon** [comment]
Aha! Cheers, I've updated my profile. <3

**Comment by keithpitt** [comment]
👍
