### ISSUE TITLE
Open source hygene - Documentation request

### ISSUE THREAD

**Issue by KevinGrandon** [buildkite/frontend#303]
Just filing this as a request for additional documentation for open source developers to get involved. Some useful information that you could add to the readme:

* How to start the server, `yarn start` I assume.
* How to setup `EMOJI_HOST`, or provide a default if possible.
* How to setup `FRONTEND_HOST`, or provide a default if possible.
* Any special network settings I might need. I see mentions of `buildkite.dev`, and I also get a `EADDRNOTAVAIL` error when trying to start the server.
* How to populate the `vendor/emojis` directory.

I'm willing to jump through a few hoops to contribute, but would love to see the barrier to contribute lowered by better documentation. Thanks!

**Comment by toolmantim** [comment]
Sorry for the confusion Kevin! Thanks for trying to contribute, and the awesome suggestions.

This repository’s readme is a little misleading, because you're not actually able to start an environment that enables you to contribute. It requires the closed-source backend at the moment. We're working to make it possible to start it up standalone and point it to buildkite.com. And when that's possible, we'll make sure to include all those details you mentioned above.

In the meantime though, we'll get the readme updated to be clearer, so you wouldn't have had to spend the time trying to get it to work.
